doranproject/urls.py
from django.contrib import admin
from django.urls import path, include
# import user.views
# import video.views # 지연
import board.views
import quiz.views
import main.views
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main.views.main,name='main'),
    path('user/', include('member.urls')),
    path('video/', include('video.urls')),
    path('board/', include('board.urls')),
    path('quiz/', include('quiz.urls')),
    path('main/', include('main.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns =[
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    
]

video/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns =[
    # 지연 : 비디오 보여주기
    path('genre/<int:genre>',views.search, name="search"),
    path('videolist/', views.videolist, name='videolist'),
    path('vdetail/<int:video_id>', views.vdetail, name='vdetail'),
    path('vcsave/<int:video_id>', views.vcsave, name='vcsave'),
    path('vdetail/<int:pk>/like', views.post_like, name='post_like'),
    #path('post_like_toggle/<int:post_id>/', views.post_like_toggle, name="post_like_toggle"),
    #path('post_like_toggle/<int:post_id>/', views.post_like_toggle, name="post_like_toggle"),
    path('vhits/<int:video_id>', views.vhits, name='vhits'), # 조회수
    
    # 윤아 : 비디오 업로드
    path('vread/', views.vread, name="vread"),
    path('vcreate/', views.vcreate, name="vcreate"),
    path('vupdate/<int:pk>', views.vupdate, name="vupdate"),
    path('vdelete/<int:pk>', views.vdelete, name="vdelete"),
    path('<int:upload_id>/', views.udetail, name='udetail'),
   
]

video/models.py
# 지연
from django.db import models
from django.utils import timezone
# title / date / video / body / link : video는 뭐쥬?
# user 연결
from django.contrib.auth.models import User

class Video(models.Model):
    title = models.CharField(max_length=200) # 영상 제목
    body = models.TextField() # 영상 내용
    date = models.DateTimeField(auto_now=True) # 게시 날짜
    video_key=models.CharField(max_length=50, null=True) # 비디오 링크
    tags = models.CharField(max_length=300, null=True) # 장르 및 태그 
    likes = models.ManyToManyField(User, related_name='likes') # 좋아요
    author=models.CharField(default = "작성자",max_length=200,blank=True) # 작성자
    vhits = models.IntegerField(null=True,blank=True,default=0) # 조회수
   # like_count = models.PositiveIntegerField(default=0) 

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:50]

class VComment(models.Model):
    vpost = models.ForeignKey(Video,on_delete=models.PROTECT) # 어느 게시물과 연관있는가
    author = models.CharField(max_length=200) #작성자
    text = models.TextField() # 댓글내용
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False) # ??

    def __str__(self):
        return self.text

    def approve(self):
        self.approved_comment = True
        self.save()

# 윤아
class Upload(models.Model):
    utitle = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    uname = models.CharField(max_length=30, blank=True)
    ubody = models.TextField()
    uvideo = models.FileField(upload_to="uploads/%Y/%m/%d", null=True)

    def __str__(self):
        return self.utitle

video/forms.py
from django import forms
from .models import Upload
# 윤아
class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['utitle', 'ubody', 'uvideo']

video/views.py
from django.shortcuts import render,get_object_or_404,redirect
import video.views
# 지연 
from .models import Video,VComment
# 윤아
from .models import Upload
from .forms import UploadForm

from django.http import HttpResponse

from django.utils import timezone
from datetime import datetime
from django.utils.dateformat import DateFormat
from member.models import *

# 로그인 데코레이터
# from django.contrib.auth.decorators import login_required

## 장르별 영상 보여주기 : minjuhui
def search(request, genre):
    if genre==1: # 랩/힙합
        vs = Video.objects.filter(tags="1")
    if genre==2: # 발라드
        vs = Video.objects.filter(tags="2")
    if genre==3: # POP
        vs = Video.objects.filter(tags="3")
    if genre==4: # 여름
        vs = Video.objects.filter(tags="4")
    if genre==5: # 밤/새벽
        vs = Video.objects.filter(tags="5")
    if genre==6: # 청량한
        vs = Video.objects.filter(tags="6")
    if genre==7: # 신나는
        vs = Video.objects.filter(tags="7")
    return render(request,'videolist.html', {'vs':vs})

## 동영상 조회수 : minjuhui
def vhits(request, video_id):
    video_detail=get_object_or_404(Video, pk=video_id)
    if video_detail.vhits==None:
        video_detail.vhits=0
    Video.objects.filter(id=video_detail.pk).update(vhits=video_detail.vhits +1)
    return redirect('/video/vdetail/'+str(video_detail.id))

# 지연 : 비디오 재생 페이지를 로드
def videolist(request):
    videos=Video.objects 
    return render(request,'videolist.html',{'videos':videos})


# 지연 : 비디오 한개 보여주는 페이지 로드
def vdetail(request,video_id):
    videos=Video.objects 
    video_detail=get_object_or_404(Video,pk=video_id)
    vcomments=VComment.objects.filter(vpost=video_detail)
    vlikes=video_detail.likes.count()

    if vlikes is None:
        vlikes="a"

    # 색 바뀌도록   
    flag="ㅎㅎ"
    video=Video.objects.all()
    polldict={}
    user=request.user
    real=[]
    for poll in Video.objects.all():
        index=poll.title
        choicedict={}
            
        choicedict[index] = poll.likes.all()
        sedex=0
        for x in choicedict[index]:
            if x==user:
                flag=False
                real.append(index)
            else:
                flag=True
    
        polldict[index]=choicedict
            #print(polldict[index])
    
        # real이 진짜 좋아요를 누른 영상들
        # video객체를 가져 오겠다
    like_videos=[]
    for y in real:
        #like_videos.append(Video.objects.filter(title=y).values('video_key'))
        like_videos.append(Video.objects.filter(title=y))
    
    yyy=[]
    for ob in like_videos:
        for o in ob:
            for vo in video:
                if vo.title==o:
                    yyy.append(vo)
                else:
                    yyy.append(o)
    yyy = list(set(yyy))                
    
            #obs=Video.objects.filter(title=ob)
        #like_videos = Video.objects.filter(title="1")        
  
    return render(request,'vdetail.html',{'video':video_detail,'flag':flag,'vcomments':vcomments,'vlikes':vlikes})

# 지연 : 댓글 저장 기능만 하는 함수
def vcsave(request,video_id):
    videos=Video.objects
    video_detail=get_object_or_404(Video,pk=video_id)
    if request.method=="POST":
        vcomment=VComment()
        vcomment.vpost=video_detail
        vcomment.author = request.user.profile.nickname
        
        vcomment.text = request.POST['text']
        vcomment.save()

        vcomments=VComment.objects.filter(vpost=video_detail)
        #return render(request,'vdetail.html',{'video':video_detail,'vcomments':vcomments})
        return redirect('/video/vdetail/'+str(video_detail.id))
        #return redirect('/video/vdetail',pk=video_id)
    else:
        return render(request, 'comment.html', {'form': form})
def post_like(request, pk):
    video_detail=get_object_or_404(Video,pk=pk)

    if request.method=="POST":
        vcomment=VComment()
        vcomment.vpost=video_detail
        vcomment.author = request.user.profile.nickname
        
        vcomment.text = request.POST['text']
        vcomment.save()

        vcomments=VComment.objects.filter(vpost=video_detail)
    # 포스트 정보 받아옴
    post = get_object_or_404(Video, pk=pk)

    # 사용자가 로그인 된건지 확인
    if not request.user.is_active:
        return redirect('vdetail',pk=pk, username=post.author, url=post.url)    

    # 사용자 정보 받아옴
    user = User.objects.get(username=request.user)
    # 좋아요에 사용자가 존재하면
    if post.likes.filter(id = user.id).exists():
        # 사용자를 지움
        
        post.likes.remove(user)
        flag=False
    else:
        # 아니면 사용자를 추가
        post.likes.add(user)
        flag=True
    vlikes=post.likes.count()
    if vlikes is None:
        vlikes="a"    
    # 포스트로 리디렉션
    #return render(request,'vdetail.html',{'video':video_detail,'flag':flag,'vlikes':vlikes})
    return redirect('/video/vdetail/'+str(video_detail.id))
    #return redirect('vdetail',pk=pk, username=post.author, url=post.url)  

# 윤아
# 비디오 업로드 목록
def vread(request):
    uploads = Upload.objects.order_by('-id')
    up = uploads.filter(uname=request.user)
    if not up: ## 현재 로그인 한 유저가 올린 비디오가 없는 경우
        return render(request, 'vread.html', {'novd':'업로드한 동영상이 없습니다.'})
    else: ## 업로드 한 비디오가 있는 경우
        return render(request, 'vread.html',{'uploads':uploads})

# 비디오 업로드 폼 생성
def vcreate(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.uname = request.user
            post.save()
            return redirect('vread')
    else:
        form = UploadForm()
        return render(request,'vcreate.html', {'form':form})

# 비디오 업로드 폼 수정
def vupdate(request, pk):
        upload = get_object_or_404(Upload, pk=pk)

        if request.method == "POST":
                form = UploadForm(request.POST, request.FILES, instance=upload) 

                if form.is_valid(): 
                        upload = form.save(commit=False) 
                        print(form.cleaned_data)
                        upload.utitle = form.cleaned_data['utitle']
                        upload.update_date=timezone.now()
                        # upload.uname = request.user
                        upload.ubody = form.cleaned_data['ubody']
                        upload.uvideo = form.cleaned_data['uvideo'] 
                        upload.save()
                        return redirect('vread') 

        else:
                form = UploadForm(instance=upload) 
                return render(request, 'vupdate.html',{'form' : form})

# 비디오 업로드 삭제
def vdelete(request, pk):
    upload = Upload.objects.get(id=pk)
    upload.delete()
    return redirect('vread')
    
# 비디오 업르드 자세히
def udetail(request, upload_id):
    upload = get_object_or_404(Upload, pk=upload_id)
    return render(request,'udetail.html',{'upload':upload})

video/templates/udetail.html
<!DOCTYPE html>
<html lang="ko">
<head>
	<title>DORANDORAN</title>
  	<!-- 부트스트랩 링크 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- 스타일을 위한 링크 -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <link rel="stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css">


    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style>
    @font-face { font-family: 'NIXGONM-Vb'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/NIXGONM-Vb.woff') format('woff'); font-weight: normal; font-style: normal; }
    @font-face { font-family: 'Chosunilbo_myungjo'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/Chosunilbo_myungjo.woff') format('woff'); font-weight: normal; font-style: normal; }
    body {
        font-family: 'NIXGONM-Vb';
        /* font-family: 'Chosunilbo_myungjo'; */
    }

    /* 주희 : 배치 맞춤*/
    .bmd {margin-top:10px;margin-left:3px;}

    .card {
      box-shadow: 5px 5px 0px rgb(235, 235, 235);
      text-align: center;
    }


    body .no-padding {
      padding: 0;
    }

    .status-upload form {
      float: center;
      width: 720px;
    }

    .card-header {
      font-family: 'NIXGONM-Vb';
      /* font-family: 'Chosunilbo_myungjo'; */
      text-align:left;
      margin-left: 30px;
      margin-right: 30px;
      background: transparent;
      border-bottom: 1px solid gray;
    }
    .card-body h4 {
      font-family: 'NIXGONM-Vb';
      /* font-family: 'Chosunilbo_myungjo'; */
      text-align:left;
      margin-left: 30px;
    }
  
    .btn {
      border-color:rgb(250, 213, 206);
      border-width:3px;
      color:#6E7783;
      font-weight:3px;
      float:right;
    }
    .btn:hover {
      background-color:#fad5ce;
      border-color:rgb(250, 213, 206);
    }


    .btn-hover {
        width: 150px;
        font-size: 16px;
        font-weight: 600;
        color: #fff;
        cursor: pointer;
        margin: 20px;
        height: 40px;
        text-align:center;
        border: none;
        background-size: 300% 100%;
        float:right;

        border-radius: 50px;
        moz-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        -webkit-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .btn-hover:hover {
        background-position: 100% 0;
        moz-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        -webkit-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .btn-hover:focus {
        outline: none;
    }

    .btn-hover.color-10 {
        background-image: linear-gradient(to right, #ed6ea0, #ec8c69, #f7186a , #FBB03B);
        box-shadow: 0 4px 15px 0 rgba(236, 116, 149, 0.75);
    }
    .comment {
      margin-top:10px;
      font-size: 20px;
    }
    @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);

    </style>

</head>
<body>

	<!--게시물 디테일-->
	<br>
	<div class="container">
	  <div class="card">
		  <h2 class="card-header">{{upload.utitle}}</h2>
      <br>
	    <div class="card-body">
        <h4>{{upload.ubody|linebreaksbr}}</h4>
        <br>
        <footer class="blockquote-footer">{{upload.uname}} | {{upload.pub_date|date:"Y-m-d"}}</footer>
        <br><br>
        {% if upload.uvideo %}
          {% if user.username == upload.uname %}
            <button class="btn btn-outline-primary bmd" onClick="location.href='{% url 'vupdate' pk=upload.pk %}'">수정</button>
            <button class="btn btn-outline-primary bmd" onClick="location.href='{% url 'vdelete' pk=upload.pk %}'">삭제</button>
            <button class="btn btn-outline-primary bmd" onClick="location.href='{{upload.uvideo.url}}'">동영상 열기</button>
          {%endif%}
          <button class="btn btn-outline-primary bmd" onClick="location.href='{% url 'vread' %}'">돌아가기</button>
        {% endif %}
	    </div>
	  </div>
    <div class="card">
      <div class="card-body">
        <p class = "comment"> 위 영상은 운영진들을 거쳐 선발해 업로드 될 예정입니다! 조금만 기다려 주세요 :) </p>
      </div>
    </div>
	</div>







</body>
</html>

video/templates/vcreate.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <!-- favicon -->
    <link rel="icon" href="/static/img/favicon-32x32.png">
    <title>DORANDORAN</title>
    <!-- 부트스트랩 링크 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- 파일업로드 아이콘 링크 -->
    <link rel="shortcut icon" href="favicon.ico">
    <!-- 외부스타일시트 링크 -->
    <link rel="stylesheet" type="text/css" href="/static/style/vcreate_style.css?after">
    <!-- 파일업로드에 필요한 js (가져온거라잘모름) -->
    <script>(function(e,t,n){var r=e.querySelectorAll("html")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);</script>
</head>

<body>
<br>
<div class="card">
    <form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card-body">
        <p class="card-title">동영상 업로드</p>
        <!-- 제목 폼 -->
        <p class="create_form">
            <label for="inp" class="inp">
                <label for = "id_utitle"></label>
                <input type="text" name="utitle" maxlength="200" required id="id_utitle" placeholder="&nbsp;">
                <span class="label">제목</span>
                <span class="border"></span>
            </label>
        </p>
        <!-- 내용 폼 -->
        <p class="create_form">
            <label for="inp" class="inp">
                <label for="id_ubody"></label>
                <textarea name="ubody" cols="60" rows="10" required id="id_ubody" placeholder="&nbsp;"></textarea>
                <span class="label">내용</span>
                <span class="border"></span>
            </label>
        </p>
        <!-- 파일 업로드 폼 -->
        <div class="box">
            <label for = "id_uvideo"></label>
			<input type="file" name="uvideo" required id="id_uvideo" class="inputfile inputfile-4" data-multiple-caption="{count} files selected" multiple />
			<label for="id_uvideo"><figure><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg></figure> <span>동영상 업로드</span></label>
        </div>
        <!-- 파일 업로드 외부 js 링크 -->
        <script src="/static/js/vcreate_script.js"></script>
        <br>
        <br>

        <!-- 저장 버튼 -->
        <button class="outline-button" type="submit">게시</button>
        <!-- 취소 버튼 -->
        <input type = "button" class = "outline-button" value = "취소" onClick="location.href='{% url 'mypage' %}'">
    </div>
    </form>
  </div>
</body>
</html>

video/templates/vread.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>DORANDORAN</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


    <style>
    
    @font-face { font-family: 'NIXGONM-Vb'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/NIXGONM-Vb.woff') format('woff'); font-weight: normal; font-style: normal; }
    body {
        /* font-family: 'Chosunilbo_myungjo'; */
        font-family: 'NIXGONM-Vb';
    }
    .btn-hover{
        border-style:none;
        background-color:#fcb69f;
    }
    table.pt {
        margin-left: auto; 
        margin-right: auto;
    }
    .btitle {
        width:600px;
    }
    #content_title {
        text-align:left;
        padding-left: 50px;
    }
    .btn-hover {
        position:relative;
        width: 150px;
        left:-150px;
        font-size: 16px;
        font-weight: 600;
        color: #fff;
        cursor: pointer;
        margin: 20px;
        height: 40px;
        text-align:center;
        border: none;
        background-size: 300% 100%;
        float:left;
        line-height:40px;


        border-radius: 50px;
        moz-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        -webkit-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }


    .btn-hover:hover {
        background-position: 100% 0;
        moz-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        -webkit-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
        color:white;
    }

    .btn-hover:focus {
        outline: none;
    }

    .btn-hover.color-10 {
            background-image: linear-gradient(to right, #ed6ea0, #ec8c69, #f7186a , #FBB03B);
        box-shadow: 0 4px 15px 0 rgba(236, 116, 149, 0.75);
    }

    .td {
    display:inline;
    }
    td a:link {
    color:black;
    }
    td a:visited {
    color:black;
    }
    td a:hover {
    text-decoration: none;
    color:gray;
    }


    .table {
    font-family: 'NIXGONM-Vb';
    width:1000px;
    margin:auto;
    }

    .table tr {
    text-align:center;
    }

    input.write {
    background-color:#fcb69f;
    }

    form{
        right:-270px;
        position: relative;
        transition: all 1s;
        width: 50px;
        height: 50px;
        background: #fcb69f;
        box-sizing: border-box;
        border-radius: 25px;
        border: 4px solid #fcb69f;
        
    }

    input.search{
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;;
        height: 42.5px;
        line-height: 30px;
        outline: 0;
        border: 0;
        display: none;
        font-size: 1em;
        border-radius: 20px;

    }

    .fa{
        box-sizing: border-box;
        padding: 10px;
        width: 42.5px;
        height: 42.5px;
        position: absolute;
        top: 0;
        right: 0;
        border-radius: 50%;
        color: white;
        text-align: center;
        font-size: 1.2em;
        transition: all 1s;
    }

    form:hover{
        width: 200px;
        cursor: pointer;
    }

    form:hover input{  
        display: block;
    }

    form:hover .fa{
        background: white;
        color: #fcb69f;
    }

    </style>
</head>
<body>

<br>
<table class="pt" width=700>
    <tr>
        <td>
          <button class="btn-hover color-10" onClick="location.href='{% url 'vcreate' %}'">동영상 업로드</button></td>
    </tr>
</table>

 {% if novd %}
  <h3 style="text-align:center">{{novd}}</h3>
  <h6 style="text-align:center">개성넘치는 동영상을 업로드하여 도란도란에 참여해보세요!</h6>
  {% else %}

<table class="table">
  <thead>
    <tr class="top">
      <th scope="col" class = "btitle">제목</th>
      <th scope="col">작성자</th>
      <th scope="col">등록일</th>
    </tr>
  </thead>
  {% for upload in uploads.all %}
  {% if user.username == upload.uname %}
  <tbody>
  <ul>
      <tr>
        <td id="content_title"><a href="{% url 'udetail' upload.id %}">{{upload.utitle}}</a></td>
        <td>{{upload.uname}}</td>
        <td>{{upload.pub_date|date:"Y-m-d"}}</td>
      </tr>
  </ul>
</tbody> 
    {% endif %}
  {% endfor %}
  {% endif %}
</table>






{% endblock %}
</body>
</html>